ONI-83: Prevent increase of item/service quantity during review.
openimis/openimis-fe-claim_js pull request #111
Opened 2023-07-24 07:24 UTC by wzglinieckisoldevelo

Ticket: https://openimis.atlassian.net/browse/ONI-83

Changes:
- Saving a review is blocked if user tries to increase item/service quantity above original value
- Warning is shown under this field

![claim_review_max_quantity](https://github.com/openimis/openimis-fe-claim_js/assets/98958634/c7986dc3-7fa0-4d29-880c-beaf81e6874b)

2023-07-24 07:38 UTC, olewandowski1 commented on src/components/ClaimForm.js
> +        if (items.length && items.filter((i) => !this.canSaveDetail(i, "item", forReview=forReview)).length) {
It should be enough to pass forReview here, no need to pass forReview=forReview.

2023-07-24 07:38 UTC, olewandowski1 commented on src/components/ClaimForm.js
> +        if (services.length && services.filter((s) => !this.canSaveDetail(s, "service", forReview=forReview)).length) {
It should be enough to pass forReview here, no need to pass forReview=forReview.

2023-07-24 07:38 UTC, olewandowski1 requested changes
I left some comments. @wzglinieckisoldevelo

2023-07-24 07:51 UTC, olewandowski1 approved these changes
LGTM @wzglinieckisoldevelo

2023-08-04 15:06 UTC, sniedzielski approved these changes

2023-08-07 07:26 UTC, dborowiecki approved these changes

2023-08-07 07:27 UTC, merged