ONI-68: In/Out-patient picker and filter added. Added setting for mandatory explanation.
openimis/openimis-fe-claim_js pull request #121
Opened 2023-08-10 22:07 UTC by wzglinieckisoldevelo

Ticket: https://openimis.atlassian.net/browse/ONI-68

DO NOT MERGE BEFORE BE PR: 

Changes:
- Added In/Out-Patient field in the claim form
- Added relevant In/Out searcher field
- Added setting required by ONI-77: Explanation is mandatory if type is IPD

2023-08-11 12:27 UTC, malinowskikam requested changes
Can we change all the relevant field names to careType/care_type?

2023-08-16 09:30 UTC, olewandowski1 commented on src/components/ClaimForm.js
> +      if (this.state.claim.visitTypeOutInPatient=="IPD" && !this.state.claim.explanation) return false;
Substitute '===' in place of '=='. Additionally, you might contemplate introducing a constant for "IPD" using a more descriptive name. As of now, the meaning of "IPD" is not entirely apparent to me.

2023-08-16 09:31 UTC, olewandowski1 commented on src/components/ClaimMasterPanel.js
> +                onChange={(v) => this.updateAttribute("visitTypeOutInPatient", v)}
Could you use more descriptive name for 'v'?

2023-08-16 09:32 UTC, olewandowski1 commented on src/components/ClaimMasterPanel.js
> +                    required={this.isExplanationMandatoryForIPD && edited.visitTypeOutInPatient=="IPD" ? true : false}
Substitute '===' in place of '=='. As in a comment above, it would be great to have a const for 'IPD' with more descriptive name.

2023-08-16 09:34 UTC, olewandowski1 commented on src/constants.js
> +export const IN_OUT_STATUS = ["IPD", "OPD"];
Create consts for those string in Array.

2023-08-16 09:41 UTC, olewandowski1 commented on src/components/InsureeSummaryPanel.js
As far as I know, we've agreed that any new component should be a function component, except when we're building upon an existing core component. If that happens, I'd recommend going with a function component too.

2023-08-16 09:43 UTC, olewandowski1 commented on src/pickers/VisitTypeOutInPatientPicker.js
As far as I know, we've agreed that any new component should be a function component, except when we're building upon an existing core component. In that case, I'd recommend going with a function component too.

2023-08-16 09:44 UTC, olewandowski1 requested changes
@wzglinieckisoldevelo I left some comments.

2023-08-22 06:41 UTC, olewandowski1 approved these changes
LGTM @wzglinieckisoldevelo

2023-08-22 07:52 UTC, dragos-dobre approved these changes

2023-08-22 07:55 UTC, merged