ONI-95: hide add claim button
openimis/openimis-fe-claim_js pull request #150
Opened 2023-10-06 13:36 UTC by olewandowski1

[ONI-95](https://openimis.atlassian.net/browse/ONI-95)

Change:
- Hide 'Create claim' button in top right corner.
- Disable 'View' button when user is not permitted.

2023-10-06 14:09 UTC, wzglinieckisoldevelo commented
LGTM

2023-10-06 17:29 UTC, sniedzielski commented
Seems that sonar checks refers to the existing code therefore LGTM this PR.

2023-10-06 17:29 UTC, sniedzielski approved these changes

2023-10-06 17:31 UTC, sniedzielski requested changes
Please refer to one comment, we can skip sonar warnings because those ones refers to old existing code, not to the new code.

2023-10-06 17:31 UTC, sniedzielski commented on src/components/ClaimInsureeSummary.js
> +  const { health_facility_id } = useSelector((store) => store.core.user.i_user);
Please change to cammel case

2023-10-06 17:32 UTC, sniedzielski commented on src/components/ClaimInsureeSummary.js
> +  const { health_facility_id } = useSelector((store) => store.core.user.i_user);
I mean into 'healthFacilityId'

2023-10-09 06:39 UTC, olewandowski1 commented on src/components/ClaimInsureeSummary.js
> +  const { health_facility_id } = useSelector((store) => store.core.user.i_user);
Done

2023-10-09 07:32 UTC, sniedzielski approved these changes

2023-10-09 07:44 UTC, dragos-dobre approved these changes

2023-10-09 07:46 UTC, merged